Feature/2 weba0001 web customer login
bc-SayakaMaeda/Mogi-Anken-Maeda pull request #3
Opened 2024-12-13 01:21 UTC by bc-SayakaMaeda

未完了：製造中

2024-12-17 02:44 UTC, bc0106976 reviewed
@bc-SayakaMaeda さん
初回レビューが完了いたしました。
ご確認よろしくお願いいたします。

2024-12-17 02:44 UTC, BC-FUKUNISHI-MAO commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +        const alphanumericRegex = /^[a-zA-Z0-9]*$/;
インデントがずれているのが気になりました。

2024-12-17 02:44 UTC, BC-FUKUNISHI-MAO commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +		//入力チェックに問題がない場合ファームを送る
コメントに誤字があります。
×ファーム
○フォーム

また、//の後に半角スペースが無いので、追加をお願いします。
こちらは横展開で確認いただきたいです。

2024-12-17 02:44 UTC, BC-FUKUNISHI-MAO commented on web-template/web-template/src/main/resources/templates/webCustomerLogin.html
> +		<form name="webCustomerLoginForm" id="webCustomerLoginForm" method="post" action="/webCustomerLogin">
【確認】
URL一覧とかは、設計時に作成していないですよね？
actionに指定している文字列がそのままURLに直結しますので、自分の中で想定外の文字列になっていないか確認をお願いいたします。

2024-12-17 02:44 UTC, BC-FUKUNISHI-MAO commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +		// フォーマットチェック
文字列長チェックが抜けていないでしょうか？
HTML側で最大文字列を設定してはいますが、いくらでも悪さはできるのでチェックも入れるのが一般的ですが、元々フロントではチェックしない想定でしょうか？

2024-12-17 02:44 UTC, BC-FUKUNISHI-MAO commented on web-template/web-template/src/main/resources/static/css/webCustomerLogin.css
> +body {
共通的な定義と、ログイン画面固有の定義がバラバラに書かれているので
ある程度まとめた方が、可読性も上がりますし、他画面で流用する際にわかりやすいです。
（後々でも良いですが、共通的な定義は共通の別cssにまとめて、全HTMLから呼び出すようにするとより管理しやすいです。）

またcssは書く順番や呼び出す順番によって優先度が変わってくるので、そこもお気をつけください。

2024-12-17 02:44 UTC, bc0106976 commented on web-template/web-template/src/main/resources/static/css/webCustomerLogin.css
> +@media (max-width: 768px) {
【確認】
今回のサイトは、全画面でレスポンシブデザインとする予定でしょうか？

その予定なら問題ないのですが
そもそもこのサイトをPCのみから使われる想定なら、必要ないかなと思ったためです。
スマホ等からも利用される想定なら、レスポンシブデザインで良いと思います。

2024-12-17 02:44 UTC, bc0106976 commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +		if (!userIdInput.value || !passwordInput.value) {
【補足】
今はテキストエリアの値取得をするのに、以下のような書き方をしてくれています。（例：利用者ID）
　const userIdInput = document.getElementById('userId');
　userIdInput.value

ですが、以下のような書き方でも値取得できると思うので共有です。（修正する必要はありません。）
　$("#userId").value

2024-12-17 08:36 UTC, bc-SayakaMaeda commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +		// フォーマットチェック
ご助言ありがとうございます。基本設計工程にて開発PMとフロントでは文字列長チェックを実装しないと合意しているため、今回は実装しません。

2024-12-17 08:37 UTC, bc-SayakaMaeda commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +		//入力チェックに問題がない場合ファームを送る
誤字大変失礼いたしました。修正致しました。
また、//のあとのスペースにつきましても修正いたしました。横展開、今後も注意致します。

2024-12-17 08:38 UTC, bc-SayakaMaeda commented on web-template/web-template/src/main/resources/templates/webCustomerLogin.html
> +		<form name="webCustomerLoginForm" id="webCustomerLoginForm" method="post" action="/webCustomerLogin">
URL一覧は基本設計工程の画面一覧で定義致しました。

2024-12-17 10:20 UTC, bc-SayakaMaeda commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +		if (!userIdInput.value || !passwordInput.value) {
ご教示ありがとうございます。

2024-12-18 02:52 UTC, bc-SayakaMaeda commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +		if (!userIdInput.value || !passwordInput.value) {
jQueryを読み込む必要があるようで、変更が多くなってしまうため、今回は当初の記述で進めることにします。

2024-12-18 02:53 UTC, bc-SayakaMaeda commented on web-template/web-template/src/main/resources/static/css/webCustomerLogin.css
> +@media (max-width: 768px) {
今回はPC想定で作成します。

2024-12-18 02:54 UTC, bc-SayakaMaeda commented on web-template/web-template/src/main/resources/static/css/webCustomerLogin.css
> +body {
共通的な定義とログイン画面固有の定義に整理してみました。今後共通化を修正する可能性がございます。

2024-12-18 02:55 UTC, bc-SayakaMaeda commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +        const alphanumericRegex = /^[a-zA-Z0-9]*$/;
Eclipse上でズレがなかったため気がつくことができませんでした。半角スペースとタブの件、ご教示いただきましてありがとうございます。すべて半角スペースでインデントになるように修正致しました。

2024-12-18 03:06 UTC, bc0106976 commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +        const alphanumericRegex = /^[a-zA-Z0-9]*$/;
確認しました。

2024-12-18 03:07 UTC, bc0106976 commented on web-template/web-template/src/main/resources/templates/webCustomerLogin.html
> +		<form name="webCustomerLoginForm" id="webCustomerLoginForm" method="post" action="/webCustomerLogin">
確認しました。

2024-12-18 03:07 UTC, bc0106976 commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +		// フォーマットチェック
確認しました。

2024-12-18 03:07 UTC, bc0106976 commented on web-template/web-template/src/main/resources/static/css/webCustomerLogin.css
> +body {
確認しました。

2024-12-18 03:08 UTC, bc0106976 commented on web-template/web-template/src/main/resources/static/css/webCustomerLogin.css
> +@media (max-width: 768px) {
確認しました。

2024-12-18 03:09 UTC, bc0106976 commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +		if (!userIdInput.value || !passwordInput.value) {
追加設定が必要とのことで失礼しました。。
今回はなしで進めるとのことで承知しました。

2024-12-18 03:10 UTC, bc0106976 commented
@bc-SayakaMaeda さん
初回レビューの指摘修正について確認完了いたしました。
追加指摘なしです。

2024-12-19 00:35 UTC, bcyutaabe requested changes
初回確認完了

2024-12-19 00:35 UTC, bcyutaabe commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +        this.src = type === 'password' ? '../static/images/icon_eye_hide.png' : '../static/images/icon_eye.png';
メッセージや画像パスは、定数定義してコード上で使いたいです。
マジックナンバーを極力減らすようなコードに修正したいです。

2024-12-19 00:35 UTC, bcyutaabe commented on web-template/web-template/src/main/resources/static/css/common.css
> +h1 {
スタイルの当て方として、h1といった汎用的に利用されるタグに適用すると自由度が下がってしまいます。
⇒h1はタイトル的に使われるものですが、ほかのページで表現したいタイトルと、このページが本当に一致するかは定かではないです
なので、nameやclass名をつけてそちらに適用する方がよいです。

2024-12-19 00:35 UTC, bcyutaabe commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +        if (!customerIDInput.value || !passwordInput.value) {
未入力をチェックするとか、正規表現を利用するといったものは、共通的な処理のように思います。
始めのタイミングから、共通処理として切り出しておく方が、後々楽になります。

2024-12-19 00:35 UTC, bcyutaabe requested changes
初回確認完了

2024-12-19 23:22 UTC, bc-SayakaMaeda commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +        if (!customerIDInput.value || !passwordInput.value) {
共通処理として切り出しました。
また、エラーメッセージがUI仕様設計書の最新版と異なってしまっていたため修正致しました。申し訳ございません。

2024-12-19 23:48 UTC, bc-SayakaMaeda commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +        this.src = type === 'password' ? '../static/images/icon_eye_hide.png' : '../static/images/icon_eye.png';
コントローラーを作成し起動させるとthymeleafの仕様になり、画像パスの記述等が変更されるため、初期表示製造時に定数定義のファイルを作成させてください。

2024-12-20 10:00 UTC, bcyutaabe requested changes
初回確認完了

2024-12-20 10:00 UTC, bcyutaabe commented on web-template/web-template/src/main/resources/static/js/validation.js
> +function validateRequiredFields(fields, errorMessage = MESSAGES.REQUIRED) {
複数件をチェックするような仕様になっていますが、1件だけをチェックする方が汎用的です（呼び出し元で複数回呼び出せばいいので）

2024-12-20 10:00 UTC, bcyutaabe commented on web-template/web-template/src/main/resources/static/js/validation.js
> +    const halfAlphanumericRegex = /^[a-zA-Z0-9]*$/;
この関数も、正規表現を変えると複数のチェックができますので、もう少し汎用的に書けると思います。

2024-12-20 10:00 UTC, bcyutaabe commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +        this.src = type === 'password' ? '../static/images/icon_eye_hide.png' : '../static/images/icon_eye.png';
_別途指摘しましたが、JSの範囲で定数を設定することができますので、そのやり方を試してください_

2024-12-20 10:00 UTC, bcyutaabe requested changes
2回目確認して戻しました

2024-12-23 11:16 UTC, bc-SayakaMaeda commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +        this.src = type === 'password' ? '../static/images/icon_eye_hide.png' : '../static/images/icon_eye.png';
コメント修正が漏れておりすみません、こちら修正push済みです。

2024-12-23 11:19 UTC, bc-SayakaMaeda commented on web-template/web-template/src/main/resources/static/css/common.css
> +h1 {
視野が狭かったです。classタグをつけてCSSを適用しました。

2024-12-23 11:46 UTC, bc-SayakaMaeda commented on web-template/web-template/src/main/resources/static/js/validation.js
> +    const halfAlphanumericRegex = /^[a-zA-Z0-9]*$/;
ご指摘ありがとうございます！汎用化しました。

2024-12-23 11:49 UTC, bc-SayakaMaeda commented on web-template/web-template/src/main/resources/static/js/validation.js
> +function validateRequiredFields(fields, errorMessage = MESSAGES.REQUIRED) {
ご指摘ありがとうございます。共通化、汎用化の可能性がないか今後意識致します。

2024-12-24 00:39 UTC, bcyutaabe requested changes
3回目確認

2024-12-24 00:39 UTC, bcyutaabe commented on web-template/web-template/src/main/resources/static/js/validation.js
> +    if (!field.value) {
fieldがnullになるケースを想定しておいてください。共通処理にして単純化したからこそ、どんな値が来ても動くようなコードにしておいてほしいです

2024-12-24 00:39 UTC, bcyutaabe commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +        let errorMessage = validateRequiredField(customerIDInput);
ここからの一連の流れが読みずらいです。
⇒最終的にisValidがtrueならサブミットするという処理で、ステータス管理が前提となっているため
エラーチェックの時点でNGならアーリーリターンするという処理でも、実装可能と思います。
その方が、むやみにステータス変数を持たなくてよく、if文の数も減らせます。

2024-12-24 00:39 UTC, bcyutaabe commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +        if (errorMessage) {
上の指摘を修正する場合、
このブロックはエラーがあった際の共通処理なので、関数化して再利用性を高める方がいいと思います

2024-12-27 00:07 UTC, bc-SayakaMaeda commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +        let errorMessage = validateRequiredField(customerIDInput);
isValidがtrueならsubmitではなく、その都度returnするように修正しました。

2024-12-27 00:09 UTC, bc-SayakaMaeda commented on web-template/web-template/src/main/resources/static/js/validation.js
> +    if (!field.value) {
fieldがnullの場合もエラーメッセージをreturnするように修正しました。
（フォーマットチェックでは、正規表現で判断するため、ここでnullの場合を追加することは不要との考えです）

2024-12-27 00:09 UTC, bc-SayakaMaeda commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +        if (errorMessage) {
修正しました。

2024-12-27 04:54 UTC, bcyutaabe commented
再レビューしてコメント返しています

2024-12-27 05:15 UTC, bcyutaabe requested changes

2024-12-27 05:15 UTC, BC-ABE-YUTA commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +        const halfAlphanumericRegex = /^[a-zA-Z0-9]*$/;
半角英数字を表す正規表現は、再利用性がありそうなので、共通処理として持っておきたいです

2024-12-27 05:15 UTC, BC-ABE-YUTA commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +        if (errorMessage) {
確認済み

2024-12-27 05:15 UTC, BC-ABE-YUTA commented on web-template/web-template/src/main/resources/static/js/validation.js
> +    if (!regex.test(field.value)) {
ここもregexが正しく指定されていない、またはfieldに値が無いと、ヌルポになりますので、しっかりチェックしてください。
また、field.valueという使い方をしていますが、共通処理としては、String文字列として受け取るほうが汎用的です。

2024-12-27 05:15 UTC, BC-ABE-YUTA commented on web-template/web-template/src/main/resources/static/js/validation.js
> +    if (!field.value) {
うーん、正規表現の方も引数が正しいかをチェックする必要があると思います。
呼出し元が「かならず値を渡してくれる」という前提ではなく、「まちがっているかもしれない」で考えてみてください。

2024-12-27 05:26 UTC, bc-SayakaMaeda commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +        const halfAlphanumericRegex = /^[a-zA-Z0-9]*$/;
修正しました。

2024-12-27 05:45 UTC, bc-SayakaMaeda commented on web-template/web-template/src/main/resources/static/js/validation.js
> +    if (!regex.test(field.value)) {
修正致しました。
nullの場合、エラーメッセージがreturenされるか以前の問題で、例外が生じてしまうということ理解が足りておりませんでした。

2024-12-27 07:10 UTC, bcyutaabe commented on web-template/web-template/src/main/resources/static/js/validation.js
> +    if (typeof value !== 'string' || !regex.test(value)) {
regexがnullの場合が確認できてないです

2024-12-27 07:11 UTC, bcyutaabe commented on web-template/web-template/src/main/resources/static/js/validation.js
> +    if (!regex.test(field.value)) {
確認しました。regexについて別途コメント入れています

2024-12-27 07:11 UTC, bcyutaabe commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +        const halfAlphanumericRegex = /^[a-zA-Z0-9]*$/;
確認済みです

2024-12-27 07:12 UTC, bcyutaabe commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +        let errorMessage = validateRequiredField(customerIDInput);
確認済みです

2024-12-27 07:12 UTC, bcyutaabe commented on web-template/web-template/src/main/resources/static/js/validation.js
> +function validateRequiredFields(fields, errorMessage = MESSAGES.REQUIRED) {
確認しました

2024-12-27 07:13 UTC, bcyutaabe commented on web-template/web-template/src/main/resources/static/css/common.css
> +h1 {
確認済み

2024-12-27 07:13 UTC, bcyutaabe commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +        if (!customerIDInput.value || !passwordInput.value) {
確認済み

2024-12-27 07:13 UTC, bcyutaabe commented on web-template/web-template/src/main/resources/static/js/webCustomerLogin.js
> +        this.src = type === 'password' ? '../static/images/icon_eye_hide.png' : '../static/images/icon_eye.png';
確認済み

2024-12-27 07:22 UTC, bc-SayakaMaeda commented on web-template/web-template/src/main/resources/static/js/validation.js
> +    if (typeof value !== 'string' || !regex.test(value)) {
修正しました。
しかし、「regexがnull」ということが掴めていません。
呼び出し先で、引数としてnullを正規表現であると入れることが可能であるという意味でしょうか？

2024-12-27 07:36 UTC, bcyutaabe commented on web-template/web-template/src/main/resources/static/js/validation.js
> +    if (typeof value !== 'string' || !regex.test(value)) {
呼出し元が以下の実装をするケースがありますよね。つまり実装者がよくわかっていないケースです。
共通処理は、利用元がうまく使ってくれる前提ではなく、下手に使われてもうまく処理を流すという思想で作るべきと考えています。

1)
validateFieldFormat(customerIDInput.value, null, MESSAGES.LOGIN_FORMAT)

2)
half_regex = null
validateFieldFormat(customerIDInput.value, half_regex, MESSAGES.LOGIN_FORMAT)

2025-01-31 09:00 UTC, merged